mqtt_server="192.168.1.69"
mqtt_user="mqtt_pi"
mqtt_port=1883
mqtt_timeout=60
mqtt_base_topic="homeassistant"
update_interval=30
logging_conf="logging.conf"

rounding=true
decimals=1
period=60
log_spikes=false
use_median=false
active_scan=false
hci_interface=[ 0 ]
batt_entities=true
encryptors= {}
report_unknown=false
whitelist=false
sensor_fahrenheit= {}
[[sensor_names]]
name='Xiaomi Køkken/kontor'
mac='4C:65:A8:DB:A8:74'

[[sensor_names]]
name='Xiaomi gang stueetage'
mac='4C:65:A8:DB:9F:A6'

[[sensor_names]]
name="Xiaomi spisestue"
mac='4C:65:A8:DB:A4:4E'

[[sensor_names]]
name="Xiaomi dagligstue"
mac="4C:65:A8:DB:9D:13"

[[sensor_names]]
name="Rasmus værelse"
mac="4C:65:A8:DB:A8:07"

[[sensor_names]]
name="Gamer rum"
mac="4C:65:A8:DB:A6:85"

[[sensor_names]]
name="Udestue"
mac="4C:65:A8:DB:A4:57"