mqtt_server="192.168.1.69"
mqtt_user="mqtt_pi"
mqtt_port=1883
mqtt_timeout=60
mqtt_discovery_prefix="homeassistant"
mqtt_topic_prefix="homeassistant"
update_interval=30

rounding=true
decimals=1
period=60
log_spikes=false
use_median=false
active_scan=false
hci_interface=[ 0 ]
batt_entities=true
encryptors= {}
report_unknown=false
whitelist=true
sensor_fahrenheit= {}
[[sensor_names]]
name='LivingRoom'
mac='4C:65:A8:DB:A4:4E'

[[sensor_names]]
name='Unknown1'
mac='4C:65:A8:DB:A8:07'

[[sensor_names]]
name='Unknown2'
mac='4C:65:A8:DB:A6:85'

#[[sensor_names]]
#name='Unknown3'
#mac='75:50:8B:E5:C7:4C'

[[sensor_names]]
name='Unknown4'
mac='4C:65:A8:DB:A8:07'

[[sensor_names]]
name='Unknown5'
mac='4C:65:A8:DB:A7:94'

[[sensor_names]]
name='Unknown6'
mac='4C:65:A8:DB:91:EC'

[[sensor_names]]
name='Unknown7'
mac='4C:65:A8:DB:9F:A6'

